### ISSUE TITLE
KG2 predicates endpoint has extra biolink prefix prepended

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1324]
Amy and I noticed this when testing #1236. It appears that the KG2 predicates endpoint  has extra biolink prefixes prepended:
![image](https://user-images.githubusercontent.com/39020520/112366669-51c85a80-8c96-11eb-8625-6aabe87fb19f.png)

maybe this is a leftover patch? @edeutsch

**Comment by edeutsch** [comment]
yes, I should remove the code that tries to compensate for the old "pre-biolink" way.
BUT, the reason that this compensation code did the wrong thing is that the prefix for Activity is Capital "Biolink:" instead of lower-case "biolink". My code decides whether prepend "biolink:" based on whether is already begins with "biolink:" (case sensitive) Although we are generally case insensitive, a lot of other work out there appears to be case sensitive.

**Comment by amykglen** [comment]
strange, I don't see any capital "Biolink:Activity" in the allowed predicate triples:
https://raw.githubusercontent.com/RTXteam/RTX/master/code/ARAX/KnowledgeSources/KG2C_allowed_predicate_triples.csv

**Comment by edeutsch** [comment]
ha! The PascalCaser is still there too.
I see the problem. Will fix shortly.

**Comment by edeutsch** [comment]
Fixed 
https://github.com/RTXteam/RTX/commit/de2dde662cd169b37d8deabead2311fb6b74d604
and deployed to production
https://arax.ncats.io/api/arax/v1.0/predicates

**Comment by amykglen** [comment]
nice! is there a reason why it still appears the old way when I do 'try it out' on the KG2 swagger page: https://arax.ncats.io/kg2/api/rtxkg2/v1.0/ui/#/predicates/predicates

**Comment by edeutsch** [comment]
ah, the reason is that I'm a dingaling and forgot roll out this fix to the most important place, kg2.
I have now rolled out the fix to all locations including kg2.
Let me know if you still see any problems.

**Comment by amykglen** [comment]
ah, nice, looks good to me now! good to close this issue @kvarforl?

**Comment by kvarforl** [comment]
Yep!
