### ISSUE TITLE
New TRAPI 1.1 Attributes

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1414]
The Attribute format has changed a bit with TRAPI 1.1. Let's use this thread to refine the attributes that we emit

Here is the reference document as it currently stands:
https://docs.google.com/document/d/1hO8SU14v0-6LCBjTn_MalLuCQgQ3YhNkMOJ_bXbX7rY
TL;DR: scroll to the bottom and look at the detailed examples

I propose that we use this new Google doc:
https://docs.google.com/document/d/1TrbHBtERoZlhzgdCrpf4RCyJhAaJEc4tzRerkQICupg

to propose, debate, refine, and agree on attributes going forward.

Please paste your examples and let's discuss.

**Comment by edeutsch** [comment]
Here is the formal documentation: https://github.com/NCATSTranslator/ReasonerAPI/blob/master/docs/reference.md#attribute-

**Comment by saramsey** [comment]
[export.csv](https://github.com/RTXteam/RTX/files/6386548/export.csv)

**Comment by saramsey** [comment]
[export.csv](https://github.com/RTXteam/RTX/files/6386553/export.csv)

**Comment by saramsey** [comment]
Folks, please help me fill out this google sheet:

https://docs.google.com/spreadsheets/d/1h4MNiGCkiEfc8iFn3cN0mI0cY85KjjjBRT2D1ni0jJE/edit?usp=sharing

**Comment by saramsey** [comment]
OK, I have completed the Google Sheet and made a TSV file and put the [TSV file in the KG2 code area](https://github.com/RTXteam/RTX/blob/master/code/kg2/kg2-provided-by-curie-to-infores-curie.tsv).

**Comment by edeutsch** [comment]
Thanks, Steve, I think it would nice to have two more columns:
name: A friendly name for the resource like ChEML, RTX KG2, DisGeNET, or potentially longer
type: where type is pulled from Matt Brush's latest plan:

•	knowledge_source (doesn't commit to being aggregator, primary, or original). 
      o	primary_knowledge_source (used for the furthest upstream source in the chain that the data creator can identify) 
             =	original_knowledge_source (used when KP is confident that the primary source is the original source)
      o	aggregator_knowledge_source (used when the KP is confident the source is an aggregator)
•	supporting_data_source (used for sources of data that a KP computes on to generate new knowledge)
This approach gives KPs options to more clearly and precisely indicate the role of each source in the retrieval of knowledge expressed in an edge. Our recommendation would be for data creators to minimal distinguish 'primary' (most upstream) from 'aggregator' (intermediate) sources - as we feel that this can be determined in nearly all cases. If the data creator is confident that the primary source was the original source, they can use the 'original_knowledge_source' property. In practice, for a linear chain of retrieval, one source should be declared 'primary' or 'original', and the rest 'aggregators'.

Shall we do that in the Google sheet first?

**Comment by amykglen** [comment]
I switched expand to use the new alternative to the `is_defined_by` attribute (for KPs we use via their APIs, plus KG1), which looks like this:
```
{
  'attribute_source':'infores:arax_ara',
  'attribute_type_id':'biolink:knowledge_provider_source',
  'description':None,
  'original_attribute_name':None,
  'value':'infores:rtx_kg2_kp',
  'value_type_id':'biolink:InformationResource',
  'value_url':None
}
```
but it seems to have broken some tests in NewFmt (I'm guessing they're tests that are looking for an 'is_defined_by' attribute...)
```
FAILED test_ARAX_overlay.py::test_FET_ex1 - AssertionError: assert 'ERROR' == 'OK'
FAILED test_ARAX_workflows.py::test_FET_ranking - AssertionError: assert 'ERROR' == 'OK'
```
think mainly these are @chunyuma's tests? (I only ran fast tests - imagine more slow ones are failing as well)

**Comment by amykglen** [comment]
and also - I pasted examples of the remaining attributes I have that need a finalized structure into the [google doc](https://docs.google.com/document/d/1TrbHBtERoZlhzgdCrpf4RCyJhAaJEc4tzRerkQICupg)

the current form is clearly not quite right, but I haven't had time to go through and propose something better for these.

**Comment by chunyuma** [comment]
> think mainly these are @chunyuma's tests? (I only ran fast tests - imagine more slow ones are failing as well)

@amykglen, I think I've solved these errors and most of FET-associated tests have passed except for except for the `test_FET_example_2`  in test_ARAX_workflow.py due to the problem reported in #1433.

**Comment by amykglen** [comment]
to clarify on where this issue is at - expand has switched to using these two new kinds of attributes (in NewFmt) described in the google doc:
```
RTX KG2 endpoint should emit this when furnishing edges:

Edge.attributes = [
	{
  	"attribute_type_id": "biolink:original_source",  
  	"value":  "infores:chembl"  
  	"value_type_id": "biolink:InformationResource", 	
  	"value_url":  "https://www.ebi.ac.uk/chembl",
  	"description": "ChEMBL",
  	"attribute_source": "infores:rtx_kg2_kp”
	},
...
ARAX should preserve this and add:

	{
  	"attribute_type_id": "biolink:knowledge_provider_source",  
  	"value": "infores:rtx_kg2_kp",  	 
  	"value_type_id": "biolink:InformationResource", 	
  	"value_url":  "https://github.com/RTXteam/RTX/tree/master/code/kg2",
  	"description": "RTX KG2 Knowledge Provider KP from NCATS Translator",
  	"attribute_source": "infores:arax_ara"  
	},
```
as well as the new decided on form for edge publications:
```
	{
  	"attribute_type_id": "biolink:has_supporting_publications",  
  	"value": [ "pmid:2012345", "pmid:2012346" ],  	 
  	"value_type_id": "biolink:Publication", 	
  	"attribute_source": "infores:semmeddb"
	}
```
all that remains to be finalized from expand's perspective are new forms for node attributes (all_categories, all_names, equivalent_curies, etc.), which I pasted examples for into the google doc.

**Comment by chunyuma** [comment]
Thanks to @amykglen's new version of the KG2c sqlite (`kg2c_v1.2_KG2.5.2.sqlite`), all FET-associated tests have passed except for the `test_FET_ranking_2` in test_ARAX_workflows.py. 

I got an error message from `resultify`:
```
  - 2021-05-06T00:14:57.808933 INFO: [] Processing action 'resultify' with parameters {'': 'true'}
  - 2021-05-06T00:14:57.808948 DEBUG: [] Applying Resultifier to Message with parameters {'': 'true'}
  - 2021-05-06T00:14:57.810142 ERROR: [UnknownError] list index out of range
  - 2021-05-06T00:14:57.810190 DEBUG: [] Cleaning up the KG to remove nodes not used in the results
  - 2021-05-06T00:14:57.810237 INFO: [] After cleaning, the KG contains 0 nodes and 0 edges
```

Hope this can be fixed once we merge `master` into `NewFmt` master.

**Comment by amykglen** [comment]
> except for the test_FET_ranking_2 in test_ARAX_workflows.py.
> 
> I got an error message from resultify:
> 
>   - 2021-05-06T00:14:57.808933 INFO: [] Processing action 'resultify' with parameters {'': 'true'}
>   - 2021-05-06T00:14:57.808948 DEBUG: [] Applying Resultifier to Message with parameters {'': 'true'}
>   - 2021-05-06T00:14:57.810142 ERROR: [UnknownError] list index out of range
>   - 2021-05-06T00:14:57.810190 DEBUG: [] Cleaning up the KG to remove nodes not used in the results
>   - 2021-05-06T00:14:57.810237 INFO: [] After cleaning, the KG contains 0 nodes and 0 edges
> Hope this can be fixed once we merge master into NewFmt master.

to clarify for everyone - this was a bug of mine in resultify that made test_FET_ranking_2 intermittently fail - it's been fixed in `master`, so should also be resolved in `NewFmt` once @finnagin merges `master` into `NewFmt`.

**Comment by finnagin** [comment]
So everything looks to be passing after the merge except the new standup query tests I added to master. Looks like something changed in how the query graph inputs are handled. Here is an example of one of those query graphs:
```
def test_diseases_treated_by_drug_issue_20():
    query = {
      "message": {
        "query_graph": {
          "edges": {
            "e01": {
              "object": "n0",
              "predicate": "biolink:treated_by",
              "subject": "n1"
            }
          },
          "nodes": {
            "n0": {
              "category": "biolink:Drug",
              "id": "DRUGBANK:DB00394"
            },
            "n1": {
              "category": "biolink:Disease"
            }
          }
        }
      }
     }
    [response, message] = _do_arax_query(query)
    assert response.status == 'OK'
    assert len(message.results) > 0
```
@edeutsch how would I go about fixing these for TRAPI 1.1?

**Comment by finnagin** [comment]
I was able to fix most of them but I'm still not sure what is wrong with this one:
```
def test_diseases_treated_by_drug_issue_20():
    query = {
      "message": {
        "query_graph": {
          "edges": {
            "e01": {
              "object": "n0",
              "predicate": "biolink:treated_by",
              "subject": "n1"
            }
          },
          "nodes": {
            "n0": {
              "category": "biolink:Drug",
              "id": "DRUGBANK:DB00394"
            },
            "n1": {
              "category": "biolink:Disease"
            }
          }
        }
      }
     }
    [response, message] = _do_arax_query(query)
    assert response.status == 'OK'
    assert len(message.results) > 0
```
which gives e the following error:
```
ERROR: [NoCategoryError] The category of query node n1 is empty. Please provide a category.
```
But there is a category specified for n1 so idk exactly what is going on here. Any ideas @edeutsch or @amykglen ?

**Comment by chunyuma** [comment]
Thanks for reporting this error @finnagin and @edeutsch , I will take a look.

**Comment by chunyuma** [comment]
ok, @finnagin, I fixed this bug. It should work now.

**Comment by edeutsch** [comment]
Clear definitions of primary, original, and aggregator knowledge sources are provided here:
https://togithub.com/NCATSTranslator/TranslatorArchitecture/issues/48#issuecomment-866045076

**Comment by amykglen** [comment]
safe to close this issue, @edeutsch?

**Comment by edeutsch** [comment]
yes, thanks!
