### ISSUE TITLE
Uncaught 'list index out of range' errors in CHPQuerier

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1591]
seeing errors on production for CHP queries... example:
```
add_qnode(ids=ENSEMBL:ENSG00000162419, key=n00)
add_qnode(categories=biolink:Drug, key=n01)
add_qedge(subject=n00, object=n01, key=e00)
expand(edge_key=e00, kp=CHP)
resultify()
filter_results(action=limit_number_of_results,max_results=100,prune_kg=true)
```
<img width="1229" alt="Screen Shot 2021-07-27 at 3 58 38 PM" src="https://user-images.githubusercontent.com/49423686/127238106-c5c50a73-506b-4792-a2b9-72a42a689269.png">

**Comment by chunyuma** [comment]
It seems like the error is because CHP team changes the old prefix `CHEMBL:XXX` to `CHEMBL.COMPOUND:XXX`. I've fixed this bug. I think it works now.

**Comment by amykglen** [comment]
ah, I see. it does look like that error is gone, although strangely the CHP Expand tests are still failing.
```
pytest -v test_ARAX_expand.py -k test_chp --runslow --runexternal

FAILED test_ARAX_expand.py::test_chp_expand_1 - AssertionError: assert (False or False or False)
FAILED test_ARAX_expand.py::test_chp_expand_2 - AssertionError: assert (False or False or False)
```

it looks like they're not finding answers anymore?

**Comment by chunyuma** [comment]
Hi @amykglen, I try to investigate why those CHP Expand tests are still failing, I found a weird thing. 

When I ran the below commands outside DSL:
```
import request
r = requests.get('http://chp.thayer.dartmouth.edu/curies/')
allowable_curies = eval(r.content)
print(allowable_curies['biolink:Drug'])
```

it returns:
```
{'CHEMBL.COMPOUND:CHEMBL1201247': ['ZOLADEX', 'GOSERELIN'], 'CHEMBL.COMPOUND:CHEMBL88': ['CYCLOPHOSPHAMIDE', 'CYTOXAN'], 'CHEMBL.COMPOUND:CHEMBL53463': ['DOXORUBICIN', 'ADRIAMYCIN', 'DOXIL', 'XL 184'], 'CHEMBL.COMPOUND:CHEMBL1201585': ['HERCEPTIN', 'TRASTUZUMAB'], 'CHEMBL.COMPOUND:CHEMBL1351': ['CARBOPLATIN'], 'CHEMBL.COMPOUND:CHEMBL3545252': ['DOCETAXEL'], 'CHEMBL.COMPOUND:CHEMBL185': ['FLUOROURACIL'], 'CHEMBL.COMPOUND:CHEMBL83': ['TAMOXIFEN'], 'CHEMBL.COMPOUND:CHEMBL1444': ['LETROZOLE', 'FEMARA'], 'CHEMBL.COMPOUND:CHEMBL428647': ['TAXOL', 'PACLITAXEL', 'ABRAXANE'], 'CHEMBL.COMPOUND:CHEMBL1399': ['ARIMIDEX', 'ANASTROZOLE'], 'CHEMBL.COMPOUND:CHEMBL1200374': ['EXEMESTANE', 'AROMASIN'], 'CHEMBL.COMPOUND:CHEMBL888': ['GEMZAR', 'GEMCITABINE'], 'CHEMBL.COMPOUND:CHEMBL92': ['TAXOTERE'], 'CHEMBL.COMPOUND:CHEMBL1773': ['XELODA'], 'CHEMBL.COMPOUND:CHEMBL924': ['ZOMETA', 'ZOLEDRONIC ACID'], 'CHEMBL.COMPOUND:CHEMBL1237023': ['DENOSUMAB'], 'CHEMBL.COMPOUND:CHEMBL1358': ['FULVESTRANT', 'FASLODEX'], 'CHEMBL.COMPOUND:CHEMBL1200775': ['LUPRON'], 'CHEMBL.COMPOUND:CHEMBL554': ['LAPATINIB'], 'CHEMBL.COMPOUND:CHEMBL1201583': ['BEVACIZUMAB', 'AVASTIN', 'BEVACIZUMAB AVASTIN', 'BEVACIZUMAB OR PLACEBO RTOG 0825'], 'CHEMBL.COMPOUND:CHEMBL417': ['EPIRUBICIN'], 'CHEMBL.COMPOUND:CHEMBL34259': ['METHOTREXATE'], 'CHEMBL.COMPOUND:CHEMBL553025': ['VINORELBINE', 'VINORELBINE TARTRATE'], 'CHEMBL.COMPOUND:CHEMBL3989401': ['PAMIDRONATE'], 'CHEMBL.COMPOUND:CHEMBL1201334': ['TRIPTORELIN'], 'CHEMBL.COMPOUND:CHEMBL1200796': ['ADRIAMYCIN-CYCLOPHOSPHAMIDE'], 'CHEMBL.COMPOUND:CHEMBL1520188': ['CLODRONATE'], 'CHEMBL.COMPOUND:CHEMBL1201568': ['NEULASTA']}
```

However, within DSL, it returns:
```
{'CHEMBL:CHEMBL1201247': ['ZOLADEX', 'GOSERELIN'], 'CHEMBL:CHEMBL88': ['CYCLOPHOSPHAMIDE', 'CYTOXAN'], 'CHEMBL:CHEMBL53463': ['DOXORUBICIN', 'ADRIAMYCIN'], 'CHEMBL:CHEMBL1201585': ['HERCEPTIN', 'TRASTUZUMAB'], 'CHEMBL:CHEMBL1351': ['CARBOPLATIN'], 'CHEMBL:CHEMBL3545252': ['DOCETAXEL'], 'CHEMBL:CHEMBL185': ['FLUOROURACIL'], 'CHEMBL:CHEMBL83': ['TAMOXIFEN'], 'CHEMBL:CHEMBL1444': ['LETROZOLE', 'FEMARA'], 'CHEMBL:CHEMBL306601': ['TAXOL'], 'CHEMBL:CHEMBL1399': ['ARIMIDEX', 'ANASTROZOLE'], 'CHEMBL:CHEMBL1200374': ['EXEMESTANE', 'AROMASIN'], 'CHEMBL:CHEMBL888': ['GEMZAR', 'GEMCITABINE'], 'CHEMBL:CHEMBL92': ['TAXOTERE'], 'CHEMBL:CHEMBL1773': ['XELODA'], 'CHEMBL:CHEMBL924': ['ZOMETA', 'ZOLEDRONIC ACID'], 'CHEMBL:CHEMBL428647': ['PACLITAXEL', 'ABRAXANE'], 'CHEMBL:CHEMBL1237023': ['DENOSUMAB'], 'CHEMBL:CHEMBL1358': ['FULVESTRANT', 'FASLODEX'], 'CHEMBL:CHEMBL1200775': ['LUPRON'], 'CHEMBL:CHEMBL554': ['LAPATINIB'], 'CHEMBL:CHEMBL1201583': ['BEVACIZUMAB', 'AVASTIN'], 'CHEMBL:CHEMBL417': ['EPIRUBICIN'], 'CHEMBL:CHEMBL34259': ['METHOTREXATE'], 'CHEMBL:CHEMBL553025': ['VINORELBINE'], 'CHEMBL:CHEMBL676': ['PAMIDRONATE'], 'CHEMBL:CHEMBL1201334': ['TRIPTORELIN'], 'CHEMBL:CHEMBL1200796': ['ADRIAMYCIN-CYCLOPHOSPHAMIDE'], 'CHEMBL:CHEMBL1520188': ['CLODRONATE'], 'CHEMBL:CHEMBL1201568': ['NEULASTA']}
```

I'm wondering if within DSL expand, it did some prefix conversions or something before calling `CHP_querier.py`.

**Comment by amykglen** [comment]
hmm - no, the main expand code never did any switching between CHEMBL and CHEMBL.COMPOUND.

I wonder if this could be a caching issue? maybe try disabling `requests_cache`? like is done here:

https://github.com/RTXteam/RTX/blob/e2eddfadc8ee2dd6dda38bf0c5aa8249d7d4662c/code/ARAX/ARAXQuery/Expand/trapi_querier.py#L157-L158

**Comment by chunyuma** [comment]
Ah, it is a caching issue. Thanks @amykglen. I fixed it and now both chp tests pass.

**Comment by amykglen** [comment]
huh, weirdly those two tests aren't passing for me in `master` after pulling latest changes. they're giving errors like these now:
```
  - 2021-07-27T23:04:40.500349 INFO: [] Expanding qedge e00 using CHP
  - 2021-07-27T23:04:40.500948 ERROR: [UncaughtError] An uncaught error was thrown while trying to Expand using CHP. Error was: Traceback (most recent call last):
  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 303, in _expand_edge
    from Expand.CHP_querier import CHPQuerier
  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/Expand/CHP_querier.py", line 1
    ../ARAXQuery/Expand/CHP_querier.py#!/bin/env python3
    ^
SyntaxError: invalid syntax
```
are you seeing that as well?

**Comment by chunyuma** [comment]
@amykglen, yes, I saw it. My mistake, please try it again. It should work now.

**Comment by amykglen** [comment]
yep, passing now!

**Comment by amykglen** [comment]
verified this looks good on production: https://arax.ncats.io/?r=17115
