### ISSUE TITLE
Clean up deprecated KG2 code, in light of Plover2.0

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2411]
created the branch `kg2cleanup` for this - plan is to do **all work in this branch**, and then only merge it to `master` after ITRB has already deleted their KG2 instances

**code to cleanup:**
- [x] make the cicd instance query the dev Plover2.0 KG2 instead of its own self-hosted KG2
- [x] update the KG2 rollout issue template
- [x] update the Dockerfile that cicd.rtx.ai uses - either make cicd.rtx.ai use the ARAX Dockerfile, or remove KG2 portions from MergedDockerfile? @sundareswarpullela will tackle this
- [x] remove the KG2 flask server directory: https://github.com/RTXteam/RTX/tree/master/code/UI/OpenAPI/python-flask-server/KG2 (note that we still need a yaml file for the KG2 smartapi registration, but that doesn't live in this directory - it's [here](https://github.com/RTXteam/RTX/tree/master/code/UI/OpenAPI/specifications/export/KG2/1.5.0))
- [x] get rid of `mode == "rtxkg2"` code in Expand
- [x] remove `kg2_querier.py` (verify pathfinder and other modules are no longer using)
  - [x] remove usages of KG2Querier in ARAX_expander.py 
  - [x] looks like Pathfinder and CRG are using it - check with Mohsen/Kevin about this 
  - [x] @mohsenht will remove related code from pathfinder on Nov. 20
  - [x] @kvnthomas98 will remove related code from CRG on Nov. 20
- [x] in KG2c build, don't create/upload the meta KG anymore (automatically provided by Plover)
- [x] update ARAX's node/edge decoration - should we still be doing this? Plover2.0 returns all attributes... do we still want to decorate other KPs' nodes/edges?
- [x] remove the 'force_local' mechanism from ARAX_expander (no longer relevant)
- [x] Update example here: https://github.com/RTXteam/RTX/blob/master/code/ARAX/Examples/kg2_api_example.py
- [x] Remove all the KG2 UI components and Apache configs and symlinks
- [x] Delete [DockerBuild/kg2-config.js](https://github.com/RTXteam/RTX/blob/kg2cleanup/DockerBuild/kg2-config.js)?
- [x] Delete [KG2-Dockerfile](https://github.com/RTXteam/RTX/blob/kg2cleanup/DockerBuild/KG2-Dockerfile)?

**other things to update:**
- [x] update hard-coded kg2 links on this page https://github.com/NCATSTranslator/Translator-All/wiki/KG2
- [x] update hard-coded kg2 links on this page https://ncatstranslator.github.io/TranslatorTechnicalDocumentation/architecture/kp/rtx-kg2/?h=rtx
  - [x] made a PR to do this (https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation/pull/102/commits/4cc25ac87b07b5e2385d1b210e1c8bcd115dfc44)
- [x] update our [spreadsheet](https://docs.google.com/spreadsheets/d/1eC3GrRW6gw5zn7XKjvaHD9KCulO-GqEaTJ3mG6PgOOY/edit?gid=0#gid=0) on ARAX, KG2, and Plover instances
- [x] look for any other hard-coded KG2 urls in wikis/documentation
- [x] update ARAX wiki with new info on Plover URL override, remove KG2 url override info
- [x] update/remove the KG2 watchdog? @edeutsch 

**deployment plan:**
- [x] @edeutsch will turn off all arax.ncats.io/kg2* endpoints the week of Nov. 11 and verify
- [x] notify Translator community that KG2 URLs are changing (SmartAPI reg will be updated accordingly, but just a heads up for anyone with hard-coded URLs)
- [x] ask ITRB to remove all kg2.x.transltr.io instances on Friday Nov. 15 (after the ITRB PROD deployment is done on Thurs Nov. 14 and verified working)
- [x] after ITRB has removed their kg2 instances, we can merge `kg2cleanup` into `master` (pending testing)

please add anything else as you think of it!

**Comment by edeutsch** [comment]
Thank you @amykglen, this is really great and thorough!

**Comment by amykglen** [comment]
so I updated the URLs on this wiki page: https://github.com/NCATSTranslator/Translator-All/wiki/KG2

which it think is what is used to populate this documentation page: https://ncatstranslator.github.io/TranslatorTechnicalDocumentation/architecture/kp/rtx-kg2/?h=rtx

but the latter hasn't shown the updates yet - not sure how that works or how often it's run... anyone know about that?

**Comment by amykglen** [comment]
hey @sundareswarpullela - thanks for your work on the Dockerfiles for this issue. wondering - in the `kg2cleanup` branch, can we delete the [KG2-Dockerfile](https://github.com/RTXteam/RTX/blob/kg2cleanup/DockerBuild/KG2-Dockerfile)?

**Comment by amykglen** [comment]
so I finally merged the `kg2cleanup` branch to `master` just now! arax.ci.transltr.io still appears to be working normally 20 minutes later.

unclear what ARAX will look like in the future but I figured getting this old code out of there would make the path forward easier no matter what.

**Comment by edeutsch** [comment]
seems great so far, thank you!

I have deployed to arax.ncats.io/devED/ and /beta/

Of note, arax.ncats.io/test/ is still on the `kg2cleanup` branch. Are we ready to return that back to `master`, or is more cleanup work planned?

**Comment by amykglen** [comment]
great, thanks! yes, I think we can return /test back to `master`.

would you or @sundareswarpullela be able to do that? I still don't have access to arax.ncats.io at this point 🙃

**Comment by edeutsch** [comment]
There are a few unchecked boxes. Anything else before we close this?

**Comment by edeutsch** [comment]
Eric to do: Clean up the Apache configs

**Comment by amykglen** [comment]
ok, I removed that old `kg2-config.js` file, and also took care of the remaining Plover-related item.

so I think after @edeutsch's clean up of the Apache configs we can close this issue out!

**Comment by edeutsch** [comment]
I have now cleaned up the Apache configs to remove KG2 services and references. And removed the symlinks in /mnt/data/orangeboard/production/RTX/code/UI/interactive

This completes the last remaining item:
- Remove all the KG2 UI components and Apache configs and symlinks

Closing.
